name: scripts_v2-sync
on:
  schedule:
    - cron: '25 19 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-scripts_v2
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.jdPAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync scripts_v2
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ClassmateLin/scripts_v2.git"
          source_branch: "master"
          destination_branch: "scripts_v2"
          github_token: ${{ secrets.jdPAT }}
